---
- name: Launch a Template Job
  hosts: localhost
  vars:
    job_tmplt_id: "1"
  vars_files:
    - vars/main.yml

  tasks:
    - name: Get Token
      uri:
        url: "{{at_base_url}}/api/v2/tokens/"
        user: "{{at_admin}}"
        password: "{{at_admin_pwd}}"
        method: POST
        validate_certs: no
        use_proxy: no
        force_basic_auth: yes
        status_code: 201
        return_content: yes
      register: at_auth_response


    - name: Build Extra Args
      set_fact:
        extra_vars: "{{ extra_vars|default({}) | combine({'at_base_url': '{{at_base_url}}' }) }}"

    - name: Build Extra Args
      set_fact:
        extra_vars: "{{ extra_vars| combine({'at_admin': '{{at_admin}}' }) }}"

    - name: Build Extra Args
      set_fact:
        extra_vars: "{{ extra_vars| combine({'at_admin_pwd': '{{at_admin_pwd}}' }) }}"

    - name: Build Extra Args
      set_fact:
        extra_vars: "{{ extra_vars| combine({'job_tmplt_id': '{{job_tmplt_id}}' }) }}"

    - name: Build Messages
      set_fact:
        extra_vars: "{{ extra_vars| combine({'messages': '{{messages}}' }) }}"

    - name: Build TaskId
      set_fact:
        extra_vars: "{{ extra_vars| combine({'task_id': '{{task_id}}' }) }}"

    - name: Build simulate_motd_failure
      set_fact:
        extra_vars: "{{ extra_vars| combine({'simulate_motd_failure': '{{simulate_motd_failure}}' }) }}"

    - name: Build extra_vars
      set_fact:
        extra_vars_dict: "{ 'extra_vars': {{ extra_vars }} }"

    - name: Build inventory
      set_fact:
        my_inv: "{ 'id': '{{inventory_id}}' }"

#    - name: Print extra_vars
#      debug: var=extra_vars

    - name: Build Body
      set_fact:
        body_var: "{{ body_var|default({}) | combine({ 'inventory': '{{my_inv}}' }) | combine({ 'extra_vars': '{{extra_vars}}' }) }}"

    - name: Launch Job
      uri:
        url: "{{at_base_url}}/api/v2/job_templates/{{job_tmplt_id}}/launch/"
        headers:
          Authorization: "Bearer {{ at_auth_response.json.token }}"
          Content-Type: "application/json"
        body_format: json
#        body: "{{ extra_vars_dict }}"
        body: "{{ body_var }}"
        method: POST
        follow_redirects: all
        validate_certs: no
        use_proxy: no
        status_code: 201
        return_content: yes
      register: job_launch_response

    - name: Print job_launch_response
      debug: var=job_launch_response 
