---
- name: Launch a Template Job
  hosts: localhost
  vars:
    job_tmplt_id: "1"
  vars_files:
    - vars/main.yml

  tasks:
    - name: Get Token
      uri:
        url: "{{at_base_url}}/api/v2/tokens/"
        user: "{{at_admin}}"
        password: "{{at_admin_pwd}}"
        method: POST
        validate_certs: no
        force_basic_auth: yes
        status_code: 201
        return_content: yes
      register: at_auth_response

    - name: Get messages
      set_fact:
        message_lines: "{{ message_lines|default([]) + [ '{{item}}' ] }}"

    - name: Print messages JSON
      debug: var=message_lines

    - name: Make messages JSON
      set_fact:
        messages_json: "{{ messages_json|default({}) + combine({ 'messages': '{{ message_lines }}' }) }}"

    - name: Print messages JSON
      debug: var=messages_json

    - name: fail temporarily
      fail:

    - name: Launch Job
      uri:
        url: "{{at_base_url}}/api/v2/job_templates/{{job_tmplt_id}}/launch/"
        headers:
          Authorization: "Bearer {{ at_auth_response.json.token }}"
          Content-Type: "application/json"
        body_format: json
        body: "{{ messages_json }}"
        method: POST
        follow_redirects: all
        validate_certs: no
        status_code: 201
        return_content: yes
      register: job_launch_response

    - name: Print job_launch_response
      debug: var=job_launch_response 
