---
#
# Simple Playbook to setup motd on Linux machine
#

- name: Setup motd
  hosts: all
  become: yes

  roles:
    - role: setup_motd

- name: Get Job Details
  hosts: localhost
  tasks:
    - name: Print Job Id
      debug:
        msg: "{{ tower_job_id }}"
      
