---
#
# Simple Playbook to setup motd on Linux machine
#

- name: Setup motd
  hosts: all
  become: yes
  vars_files:
    - vars/main.yml

  roles:
    - role: setup_motd

- name: Get Job Details
  hosts: localhost
  tasks:
    - name: Print Job Id
      debug:
        msg: "{{ tower_job_id }}"

    - name: Get Token
      uri:
        url: "{{at_base_url}}/api/v2/tokens/"
        user: "{{at_admin}}"
        password: "{{at_admin_pwd}}"
        method: POST
        validate_certs: no
        force_basic_auth: yes
        status_code: 201
        return_content: yes
      register: at_auth_response

    - name: Get Job Events
      uri:
        url: "{{at_base_url}}/api/v2/jobs/{{tower_job_id}}/job_events/"
        headers:
          Authorization: "Bearer {{ at_auth_response.json.token }}"
          Content-Type: "application/json"
        method: GET
        follow_redirects: all
        validate_certs: no
        return_content: yes
      register: job_events

    - name: Initialize EventData JSON
      set_fact:
        eventdata: []

    - name: Make EventData JSON
#      set_fact:
#        eventdata: "{{ eventdata + [ { 'event_name': '{{job_event.event}}', 'failed': '{{job_event.failed}}' } ] }}"
      debug:
        msg: "Event Name: {{job_event.event}}, Event Failed: {{job_event.failed}}"
      loop: "{{job_events.json.results}}"
      loop_control:
        loop_var: job_event
      when:
        - job_event.event_data is defined
        - job_event.event_data.task is defined
        - job_event.play is defined
        - job_event.play == "Setup motd"

#    - name: Print Failed Event Data
#      debug:
#        msg: "{{job_event.event}}"
#      loop: "{{ job_events.json.results }}"
#      loop_control:
#        loop_var: job_event
#      when:
#        - job_event.failed|bool 

    - name: Print EventData JSON
      debug:
        var: "{{eventdata}}"
