---
# tasks file for handle_job_events

- name: Get Token
  uri:
    url: "{{at_base_url}}/api/v2/tokens/"
    user: "{{at_admin}}"
    password: "{{at_admin_pwd}}"
    method: POST
    validate_certs: no
    force_basic_auth: yes
    status_code: 201
    return_content: yes
  register: at_auth_response
  delegate_to: localhost

- name: Get Job Events
  uri:
    url: "{{at_base_url}}/api/v2/jobs/{{tower_job_id}}/job_events/"
    headers:
      Authorization: "Bearer {{ at_auth_response.json.token }}"
      Content-Type: "application/json"
    method: GET
    follow_redirects: all
    validate_certs: no
    return_content: yes
  register: job_events
  delegate_to: localhost

- name: Initialize EventData JSON
  set_fact:
    failed_event_data: []

- name: Capture failed event data
  set_fact:
    failed_event_data: "{{ failed_event_data  + [{ 'task': '{{job_event.event_data.task}}', 'failed': '{{job_event.failed|bool}}' }] }}"
  loop: "{{ job_events.json.results }}"
  loop_control:
    loop_var: job_event
  when:
    - job_event.failed is defined
    - job_event.failed

- name: Print failed_event_data
  debug: var=failed_event_data
