---
# tasks file for setup_motd

- name: Setup message
  template:
    src: motd.j2
    dest: /etc/motd

- name: Fail Temporarily
  fail:
    msg: "File Exists"
  when:
    - simulate_motd_failure|bool
