---
# tasks file for setup_motd

- name: Setup message
  template:
    src: motd.j2
    dest: /etc/motd

- name: Check file exists
  stat:
    path: /etc/motd
  register: motd_file

- name: Fail Temporarily
  fail:
    msg: "File Exists"
  when:
    - motd_file.stat.exists 
